### PR TITLE
A Flask router style Decoractor

### PR DESCRIPTION
**Pull request by RyanKung**
1) Should not use `callable` as parameter name; 
2) Added a decorator to :class:`Router` for supporting `flask` like router.

### CODE REVIEW

**Comment by lsbardel** [comment]
Interesting method.
How is one supposed to use it?

When adding new code the standard practice is to add an example if possible and, importantly, test coverage (without test nothing get merged).

**Comment by RyanKung** [comment]
@lsbardel Here is the unit test and examples.

**Comment by lsbardel** [comment]
Thanks for this.
Can you make this pull request against the `dev` branch?
It will go into pulsar 2.0

**Comment by RyanKung** [comment]
Hi @lsbardel , plz check https://github.com/quantmind/pulsar/pull/280 and https://github.com/quantmind/pulsar/pull/279 which is for `dev` branch

**Comment by lsbardel** [comment]
replaced by #279 agains the dev branch

**Pull request closed without merging**
