### PR TITLE
Fix: handle HEAD method empty response on errors like 404

### PR DESCRIPTION
**Pull request by s-sokolko**
I've noticed that if you're using pulsar-cloud with its Asyncbotocore, you can sometimes experience infinite waiting. This happens when you try to call things like:
`
from cloud.aws import AsyncioBotocore  
self._s3 = AsyncioBotocore('s3', aws_region, aws_access_key_id=aws_access_key_id,
                                       aws_secret_access_key=aws_secret_access_key)  
self._obj_head = await self._s3.head_object(Bucket=self._aws_bucket, Key=guid)
`
So, you try to make HEAD on non-exisent guid. S3 returns a "chunked" response with code 404. But the request method was HEAD, so the response body is empty. Nevertheless the whole application hangs awaiting for some data to be received and never returns.
After some investigation and looking closely at pulsar/utils/httpurl.py I noticed that _parse_headers method checks for `has_empty_content(status, self._method)` and sets `self._clen_rest = self._clen = clen` correctly, but _parse_body doesn't handle chunked empty response correctly. So, I made this patch and now it works for me. What do you think: is this solution correct?

### CODE REVIEW

**Comment by lsbardel** [comment]
Tests are failing which suggests your patch has problems.

**Comment by s-sokolko** [comment]
Done, tests are working now

**Comment by lsbardel** [comment]
OK, how can I validate this use case?
What are the full response headers you get back from s3?

**Comment by s-sokolko** [comment]
@lsbardel  This happens when I run obj_head method on non-existent object resulting in HEAD HTTP request returning empty HTTP response with the status of 404 error. The response also has a header of chunked content. Maybe this is incorrect, but S3 does this, so this patch allows handle S3 response correctly.

**Comment by lsbardel** [comment]
Thanks for reporting this issue.
This is now fixed in master.
The fix is different from your patch because the http parser must be compatible with the C [http-parser](https://github.com/benoitc/http-parser) for speed.

**Pull request closed without merging**
